[project]
name = "uni-framedle"
version = "0.1.0"
description = "test your knowledge of UNI2 moves with this fun package!"
readme = "README.md"
authors = [
    { name = "Dylan Berry", email = "dylanjberry@icloud.com" }
]
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.3",
]

[project.scripts]
uni-framedle = "uni_framedle:uniframedle"

[tool.uv.build-backend]
source-include = ["data/uni2_moves_all.csv"]

[tool.setuptools.package-data]
"some-package" = ["src/uni-framedle/uni2_moves_all.csv"]

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
